name: Push OpenSIPS Control Panel Image in Docker Hub

on:
  push:
  repository_dispatch:
    types: [OpenSIPS CP trigger]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Determine tag
      run: |
        if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
          echo "DOCKER_TAG=${{ github.event.client_payload.docker_tag }}" >> $GITHUB_ENV
        else
          echo "DOCKER_TAG=latest" >> $GITHUB_ENV
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: opensips/opensips-cp:${{ env.DOCKER_TAG }}
